# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: xronocode.Mark
PackageVersion: 2.2.0-beta
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/xronocode/mark/releases/download/v2.2.0-beta/Mark_2.2.0-beta_x64-setup.exe
  InstallerSha256: 67ff85a07e503ed3d0b54f8001a53880ca7f736a8ab455ee71f650310a456708
  InstallModes:
  - silent
  - silentWithProgress
  AppsAndFeaturesEntries:
  - DisplayName: Mark
    DisplayVersion: 2.2.0-beta
    Publisher: xronocode
  ReleaseDate: 2026-10-07
ManifestType: installer
ManifestVersion: 1.12.0
